name: Build and push from dfx-dev folder

on:
  push:
    branches: 
      - main
    paths:
      - 'dfx-dev/**'

jobs:
  dfx-dev:
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GCP Registry
        uses: docker/login-action@v1 
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building base Rust/DFX image
        uses: docker/build-push-action@v2
        with:
          push: true
          secrets: GIT_AUTH_TOKEN=${{ secrets.PAT_TOKEN }}
          context: "{{defaultContext}}:dfx-dev"
          tags: |
            ghcr.io/${{ github.repository_owner }}/dfx-dev-base:latest
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/dfx-dev-base:latest
          file: ./Dockerfile.base

      - name: Building Dfinity nns tool and canisters wasms
        uses: docker/build-push-action@v2
        with:
          push: true
          secrets: GIT_AUTH_TOKEN=${{ secrets.PAT_TOKEN }}
          context: "{{defaultContext}}:dfx-dev"
          tags: |
            ghcr.io/${{ github.repository_owner }}/dfx-dev-full:latest
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/dfx-dev-full:latest
          file: ./Dockerfile.wasm
