name: Build and push containers

on:
  push:
    branches: 
      - main
    paths:
      -dfx-dev/**

jobs:
  dfx-dev:
    runs-on: ubuntu-latest
    
    steps:

      # - name: Checkout repository and submodules
      #   uses: actions/checkout@v3
      #   with:
      #     submodules: recursive
      #     token: ${{ secrets.PAT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GCP Registry
        uses: docker/login-action@v1 
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Building base Rust/DFX image
        uses: docker/build-push-action@v2
        with:
          secrets: GIT_AUTH_TOKEN=${{ secrets.PAT_TOKEN }}
          context: "{{defaultContext}}:dfx-dev"
          # build-contexts: |
          #   project=./dfx-server
          tags: dfx-dev/base:latest
          file: ./Dockerfile.base

      - name: Building Dfinity nns tool and canisters wasms
        uses: docker/build-push-action@v2
        with:
          secrets: GIT_AUTH_TOKEN=${{ secrets.PAT_TOKEN }}
          context: "{{defaultContext}}:dfx-dev"
          # build-contexts: |
          #   project=./dfx-server
          tags: dfx-dev/full:latest
          file: ./Dockerfile.wasm
