name: rust_dfx_base_image

on:
  workflow_dispatch:
    # Just run it
  push:
    branches: 
      - main
    paths:
      - 'ic-dev/Dockerfile.base'

env:
  BUILD_TAG: r1.60-d0.9.3

jobs:
  ic-dev-base-image:
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GCP Registry
        uses: docker/login-action@v1 
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building base Rust/DFX image
        uses: docker/build-push-action@v2
        with:
          push: true
          secrets: GIT_AUTH_TOKEN=${{ secrets.PAT_TOKEN }}
          context: "{{defaultContext}}:ic-dev"
          tags: |
            ghcr.io/${{ github.repository_owner }}/ic-dev-base:latest
            ghcr.io/${{ github.repository_owner }}/ic-dev-base:${{ env.BUILD_TAG }}
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/ic-dev-base:latest
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/ic-dev-base:${{ env.BUILD_TAG }}
          file: ./Dockerfile.base
