name: ic_binaries

on:
  workflow_dispatch:
    # Just run it
  push:
    branches: 
      - main
    paths:
      - 'ic-dev/Dockerfile.ic.bin'

env:
  BUILD_TAG: latest

jobs:
  ic-binaries:
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GCP Registry
        uses: docker/login-action@v1 
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building Dfinity nns tool and canisters wasms
        uses: docker/build-push-action@v2
        with:
          push: true
          secrets: GIT_AUTH_TOKEN=${{ secrets.PAT_TOKEN }}
          context: "{{defaultContext}}:ic-dev"
          build-args: |
            IC_BUILD_BRANCH=rebased-2022-02-17
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/ic-dev-base:latest
          tags: |
            ghcr.io/${{ github.repository_owner }}/ic-bin:latest
            ghcr.io/${{ github.repository_owner }}/ic-bin:${{ env.BUILD_TAG }}
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/ic-bin:latest
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/ic-bin:${{ env.BUILD_TAG }}
          file: ./Dockerfile.ic.bin
