on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - name: I'm .K
        run: |
          echo "Everything is .K"
          echo "ENVIRONMENT"
          env
